# https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

steps:
  - name: Hello world action
#   with: # Set the secret as an input
#     super_secret: ${{ secrets.TEST_SECRET }}
    env: # Or as an environment variable
      test_secret: ${{ secrets.TEST_SECRET }}