name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Initial Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Get set
        run: |
          echo "::set-env name=test_secret::${{secrets.TEST_SECRET}}"

      - name: Build
        run: |
          npm ci
          npm run build
