# This is a basic workflow to help you get started with Actions

name: CI-with-env

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:

    - name: Git checkout # repo under $GITHUB_WORKSPACE
      uses: actions/checkout@v2

    - name: Use Node 12
      uses: actions/setup-node@v2-beta
#     uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Build
      env:
        CI: true
        test_secret: ${{ secrets.TEST_SECRET }}
      run: |
        npm install
        npm install --save-dev webpack
        npm install --save-dev webpack-cli
        npm run-script build
        echo test_secret: ${#test_secret}

#   - name: Deploy
#     uses: JamesIves/github-pages-deploy-action@releases/v3
#     with:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       BRANCH: gh-pages
#       FOLDER: build
